/**
 * HabitPulse - Core Application Engine
 * Personal Habit Tracker & Task Scheduler (PWA + Google Sheets Backend)
 */

document.addEventListener('DOMContentLoaded', () => {
  
  // ==========================================================================
  // 1. APP STATE & INITIALIZATION
  // ==========================================================================
  const STORAGE_KEY = 'habitpulse_state_v1';
  
  const getTodayStr = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  const defaultState = {
    selectedDate: getTodayStr(),
    dailyTasks: [
      {
        id: 'task-def-1',
        date: getTodayStr(),
        taskName: 'Sholat Dzuhur Berjama\'ah',
        category: 'Ibadah',
        timeStart: '12:15',
        timeEnd: '12:45',
        status: 'Pending',
        isAutoGenerated: true
      },
      {
        id: 'task-def-2',
        date: getTodayStr(),
        taskName: 'Program Lari Pagi 5km',
        category: 'Olahraga',
        timeStart: '06:00',
        timeEnd: '07:00',
        status: 'Done',
        isAutoGenerated: true
      },
      {
        id: 'task-def-3',
        date: getTodayStr(),
        taskName: 'Belajar Bahasa Inggris (Listening)',
        category: 'Kewajiban',
        timeStart: '20:00',
        timeEnd: '20:45',
        status: 'Pending',
        isAutoGenerated: false
      }
    ],
    ibadahLogs: {
      // Keyed by date "YYYY-MM-DD"
    },
    goalLogs: {
      // Keyed by date "YYYY-MM-DD"
    },
    nofap: {
      streak: 5,
      bestStreak: 12,
      startDate: getTodayStr(),
      lastCheckInDate: getTodayStr()
    },
    customGoalsList: [
      { id: 'cg-1', title: 'Baca Buku Motivasi', type: 'number', unit: 'halaman', target: 15 },
      { id: 'cg-2', title: 'Mandi Air Dingin', type: 'boolean', unit: '', target: 1 }
    ],
    customGoalLogs: {
      // Keyed by date -> goalId: value
    },
    exercisePlan: {
      title: 'Program Kalistenik & Lari Ultah 25km',
      targetDate: '2026-12-31',
      timeEst: '06:00 - 07:00',
      menus: [
        'Lari Pagi 5 km (Pace 6:00)',
        'Push Up 3 Set x 15 Reps',
        'Plank 3 Set x 60 Detik'
      ]
    },
    exerciseDailyLogs: {
      // Keyed by date -> array of { exerciseName, status }
    },
    settings: {
      gasUrl: '',
      lastSynced: null
    }
  };

  let state = loadState();

  function loadState() {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        return { ...defaultState, ...parsed };
      }
    } catch (e) {
      console.error('Failed to load local state:', e);
    }
    return defaultState;
  }

  function saveState() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
      updateSyncStatusUI();
    } catch (e) {
      console.error('Failed to save state to localStorage:', e);
    }
  }

  // Ensure default structure for selected date
  function ensureDateLogs(dateStr) {
    if (!state.ibadahLogs[dateStr]) {
      state.ibadahLogs[dateStr] = {
        prayers: { Subuh: "Jama'ah", Dzuhur: "Jama'ah", Ashar: "Ada'", Maghrib: "Jama'ah", Isya: "Jama'ah" },
        sunnah: { Dhuha: true, Tahajud: false },
        quranMinutes: 20
      };
    }
    if (!state.goalLogs[dateStr]) {
      state.goalLogs[dateStr] = { englishMinutes: 30 };
    }
    if (!state.customGoalLogs[dateStr]) {
      state.customGoalLogs[dateStr] = {};
    }
    if (!state.exerciseDailyLogs[dateStr]) {
      state.exerciseDailyLogs[dateStr] = state.exercisePlan.menus.map(name => ({
        exerciseName: name,
        status: 'Pending'
      }));
    }
  }

  // ==========================================================================
  // 2. NAVIGATION & TABS SYSTEM
  // ==========================================================================
  const navItems = document.querySelectorAll('.nav-item, .mobile-nav-item');
  const tabPanes = document.querySelectorAll('.tab-pane');
  const currentTabTitle = document.getElementById('currentTabTitle');
  const currentTabSubtitle = document.getElementById('currentTabSubtitle');
  const btnHeaderAction = document.getElementById('btnHeaderAction');

  const tabTitles = {
    'daily-tasks': { title: 'Daily Tasks', subtitle: 'Kelola tugas & rutinitas harian terintegrasi', btnText: 'Tambah Tugas', modal: 'modalTask' },
    'ibadah': { title: 'Modul Ibadah', subtitle: 'Catatan sholat wajib, sunnah, dan Al-Qur\'an', btnText: 'Auto-Fill Today', action: 'autofillIbadah' },
    'goals': { title: 'Personal Goals & Streak', subtitle: 'Lacak Bahasa Inggris, NoFap streak, dan custom goals', btnText: 'Tambah Custom Goal', modal: 'modalCustomGoal' },
    'exercise': { title: 'Modul Olahraga', subtitle: 'Scheduled exercise plan & menu harian', btnText: 'Atur Plan Latihan', modal: 'modalExercisePlan' },
    'sync-settings': { title: 'Sync & Settings', subtitle: 'Hubungkan ke Google Sheets API & PWA configuration', btnText: 'Upload Data Now', action: 'pushSync' }
  };

  function switchTab(tabId) {
    navItems.forEach(item => {
      if (item.dataset.tab === tabId) {
        item.classList.add('active');
      } else {
        item.classList.remove('active');
      }
    });

    tabPanes.forEach(pane => {
      if (pane.id === `tab-${tabId}`) {
        pane.classList.add('active');
      } else {
        pane.classList.remove('active');
      }
    });

    const info = tabTitles[tabId] || tabTitles['daily-tasks'];
    currentTabTitle.textContent = info.title;
    currentTabSubtitle.textContent = info.subtitle;
    
    btnHeaderAction.innerHTML = `<i class="fa-solid fa-plus"></i> <span>${info.btnText}</span>`;
    btnHeaderAction.onclick = () => {
      if (info.modal) openModal(info.modal);
      else if (info.action === 'autofillIbadah') autoSyncRoutinesForDate(state.selectedDate);
      else if (info.action === 'pushSync') pushToGoogleSheets();
    };
  }

  navItems.forEach(item => {
    item.addEventListener('click', (e) => {
      e.preventDefault();
      const tabId = item.dataset.tab;
      switchTab(tabId);
    });
  });

  // Date picker initialization
  const datePicker = document.getElementById('globalDatePicker');
  datePicker.value = state.selectedDate;
  datePicker.addEventListener('change', (e) => {
    state.selectedDate = e.target.value;
    ensureDateLogs(state.selectedDate);
    saveState();
    renderAllModules();
  });

  // ==========================================================================
  // 3. REAL-TIME ACTIVE TASK BANNER ENGINE (Header Banner - Requirement 2.A)
  // ==========================================================================
  const liveClockDisplay = document.getElementById('liveClockDisplay');
  const activeTaskName = document.getElementById('activeTaskName');
  const activeTaskCategory = document.getElementById('activeTaskCategory');
  const activeTaskTime = document.getElementById('activeTaskTime');
  const activeTaskStatusTag = document.getElementById('activeTaskStatusTag');
  const btnQuickCompleteActive = document.getElementById('btnQuickCompleteActive');
  const nextTaskName = document.getElementById('nextTaskName');
  const nextTaskTime = document.getElementById('nextTaskTime');

  let currentActiveTaskId = null;

  function updateRealTimeClock() {
    const now = new Date();
    const hours = String(now.getHours()).padStart(2, '0');
    const mins = String(now.getMinutes()).padStart(2, '0');
    const secs = String(now.getSeconds()).padStart(2, '0');
    liveClockDisplay.textContent = `${hours}:${mins}:${secs}`;
    
    // Check banner state every minute or clock tick
    updateActiveTaskBanner(now);
  }

  function updateActiveTaskBanner(nowDate) {
    const nowHoursMins = `${String(nowDate.getHours()).padStart(2, '0')}:${String(nowDate.getMinutes()).padStart(2, '0')}`;
    const todayStr = getTodayStr();

    // Filter tasks for today
    const todayTasks = state.dailyTasks.filter(t => t.date === todayStr);

    let currentTask = null;
    let nextTask = null;

    // Sort today's tasks by timeStart
    todayTasks.sort((a, b) => a.timeStart.localeCompare(b.timeStart));

    for (let task of todayTasks) {
      if (nowHoursMins >= task.timeStart && nowHoursMins <= task.timeEnd) {
        currentTask = task;
      } else if (nowHoursMins < task.timeStart && (!nextTask || task.timeStart < nextTask.timeStart)) {
        nextTask = task;
      }
    }

    if (currentTask) {
      currentActiveTaskId = currentTask.id;
      activeTaskName.textContent = currentTask.taskName;
      activeTaskCategory.innerHTML = `<i class="fa-solid fa-tag"></i> ${currentTask.category}`;
      activeTaskTime.querySelector('span').textContent = `${currentTask.timeStart} - ${currentTask.timeEnd}`;
      
      activeTaskStatusTag.className = 'banner-status-tag active-now';
      activeTaskStatusTag.innerHTML = `<i class="fa-solid fa-play-circle"></i> Sedang Berlangsung (${currentTask.status})`;
      
      btnQuickCompleteActive.style.display = currentTask.status === 'Done' ? 'none' : 'inline-flex';
    } else {
      currentActiveTaskId = null;
      activeTaskName.textContent = 'Tidak Ada Tugas Aktif Saat Ini';
      activeTaskCategory.innerHTML = `<i class="fa-solid fa-clock"></i> Istirahat / Free Time`;
      activeTaskTime.querySelector('span').textContent = `--:-- - --:--`;
      
      activeTaskStatusTag.className = 'banner-status-tag';
      activeTaskStatusTag.innerHTML = `<i class="fa-solid fa-mug-hot"></i> Idle`;
      btnQuickCompleteActive.style.display = 'none';
    }

    if (nextTask) {
      nextTaskName.textContent = nextTask.taskName;
      nextTaskTime.textContent = `(${nextTask.timeStart} - ${nextTask.timeEnd})`;
    } else {
      nextTaskName.textContent = 'Tidak ada tugas berikutnya hari ini';
      nextTaskTime.textContent = '';
    }
  }

  btnQuickCompleteActive.addEventListener('click', () => {
    if (currentActiveTaskId) {
      const task = state.dailyTasks.find(t => t.id === currentActiveTaskId);
      if (task) {
        task.status = 'Done';
        saveState();
        renderDailyTasks();
        updateActiveTaskBanner(new Date());
        showToast('Tugas aktif berhasil ditandai Done!', 'success');
      }
    }
  });

  setInterval(updateRealTimeClock, 1000);

  // ==========================================================================
  // 4. MODUL DAILY TASK & AUTO-INTEGRATION (Requirement 2.B)
  // ==========================================================================
  const dailyTasksTableBody = document.getElementById('dailyTasksTableBody');
  const emptyTasksState = document.getElementById('emptyTasksState');
  const btnEmptyAddTask = document.getElementById('btnEmptyAddTask');
  const btnAutoSyncDaily = document.getElementById('btnAutoSyncDaily');
  const filterChips = document.querySelectorAll('.chip[data-filter]');

  let activeCategoryFilter = 'all';

  filterChips.forEach(chip => {
    chip.addEventListener('click', () => {
      filterChips.forEach(c => c.classList.remove('active'));
      chip.classList.add('active');
      activeCategoryFilter = chip.dataset.filter;
      renderDailyTasks();
    });
  });

  function renderDailyTasks() {
    dailyTasksTableBody.innerHTML = '';
    const dateStr = state.selectedDate;

    let tasks = state.dailyTasks.filter(t => t.date === dateStr);

    if (activeCategoryFilter !== 'all') {
      tasks = tasks.filter(t => t.category === activeCategoryFilter);
    }

    tasks.sort((a, b) => a.timeStart.localeCompare(b.timeStart));

    if (tasks.length === 0) {
      emptyTasksState.style.display = 'block';
      document.getElementById('dailyTasksTable').style.display = 'none';
      return;
    }

    emptyTasksState.style.display = 'none';
    document.getElementById('dailyTasksTable').style.display = 'table';

    tasks.forEach((task, idx) => {
      const tr = document.createElement('tr');
      
      const categoryBadges = {
        'Ibadah': 'badge-emerald',
        'Olahraga': 'badge-amber',
        'Kewajiban': 'badge-indigo',
        'Bermain': 'badge-pink',
        'Kebutuhan': 'badge-cyan'
      };

      const statusBadges = {
        'Done': 'badge-emerald',
        'Overdue': 'badge-danger',
        'Pass': 'badge-outline',
        'Pending': 'badge-amber'
      };

      tr.innerHTML = `
        <td><strong>${idx + 1}</strong></td>
        <td>
          <strong style="${task.status === 'Done' ? 'text-decoration: line-through; opacity: 0.6;' : ''}">${escapeHtml(task.taskName)}</strong>
          ${task.isAutoGenerated ? '<br><small class="text-muted" style="font-size:0.7rem;"><i class="fa-solid fa-wand-magic-sparkles"></i> Auto Routine</small>' : ''}
        </td>
        <td><span class="badge ${categoryBadges[task.category] || 'badge-outline'}">${task.category}</span></td>
        <td><i class="fa-regular fa-clock text-muted"></i> <strong>${task.timeStart} - ${task.timeEnd}</strong></td>
        <td><span class="badge ${statusBadges[task.status] || 'badge-outline'}">${task.status}</span></td>
        <td style="text-align: right;">
          <button class="btn btn-outline btn-sm btn-action-done" data-id="${task.id}" title="Toggle Done">
            <i class="fa-solid ${task.status === 'Done' ? 'fa-arrow-rotate-left' : 'fa-check'}"></i>
          </button>
          <button class="btn btn-outline btn-sm btn-action-edit" data-id="${task.id}" title="Edit">
            <i class="fa-solid fa-pen"></i>
          </button>
          <button class="btn btn-outline btn-sm btn-action-delete" data-id="${task.id}" title="Hapus">
            <i class="fa-solid fa-trash text-danger"></i>
          </button>
        </td>
      `;

      dailyTasksTableBody.appendChild(tr);
    });

    // Attach Event Listeners to Action Buttons
    dailyTasksTableBody.querySelectorAll('.btn-action-done').forEach(btn => {
      btn.addEventListener('click', () => {
        const t = state.dailyTasks.find(x => x.id === btn.dataset.id);
        if (t) {
          t.status = t.status === 'Done' ? 'Pending' : 'Done';
          saveState();
          renderDailyTasks();
          updateActiveTaskBanner(new Date());
        }
      });
    });

    dailyTasksTableBody.querySelectorAll('.btn-action-edit').forEach(btn => {
      btn.addEventListener('click', () => {
        const t = state.dailyTasks.find(x => x.id === btn.dataset.id);
        if (t) {
          document.getElementById('taskEditId').value = t.id;
          document.getElementById('taskNameInput').value = t.taskName;
          document.getElementById('taskCategorySelect').value = t.category;
          document.getElementById('taskStatusSelect').value = t.status;
          document.getElementById('taskTimeStart').value = t.timeStart;
          document.getElementById('taskTimeEnd').value = t.timeEnd;
          document.getElementById('modalTaskTitle').textContent = 'Edit Tugas';
          openModal('modalTask');
        }
      });
    });

    dailyTasksTableBody.querySelectorAll('.btn-action-delete').forEach(btn => {
      btn.addEventListener('click', () => {
        if (confirm('Apakah Anda yakin ingin menghapus tugas ini?')) {
          state.dailyTasks = state.dailyTasks.filter(x => x.id !== btn.dataset.id);
          saveState();
          renderDailyTasks();
          updateActiveTaskBanner(new Date());
          showToast('Tugas telah dihapus', 'success');
        }
      });
    });
  }

  // Auto Sync Ibadah & Exercise routines into today's task list (Requirement 2.B)
  function autoSyncRoutinesForDate(dateStr) {
    let addedCount = 0;

    // Standard Prayer Schedule Tasks
    const prayerRoutines = [
      { name: 'Sholat Subuh Berjama\'ah', start: '04:30', end: '05:00' },
      { name: 'Sholat Dzuhur Berjama\'ah', start: '12:15', end: '12:45' },
      { name: 'Sholat Ashar Berjama\'ah', start: '15:30', end: '16:00' },
      { name: 'Sholat Maghrib Berjama\'ah', start: '18:15', end: '18:45' },
      { name: 'Sholat Isya Berjama\'ah', start: '19:30', end: '20:00' }
    ];

    prayerRoutines.forEach(p => {
      const exists = state.dailyTasks.some(t => t.date === dateStr && t.taskName.includes(p.name));
      if (!exists) {
        state.dailyTasks.push({
          id: 'task-auto-' + Date.now() + '-' + Math.random().toString(36).substr(2, 4),
          date: dateStr,
          taskName: p.name,
          category: 'Ibadah',
          timeStart: p.start,
          timeEnd: p.end,
          status: 'Pending',
          isAutoGenerated: true
        });
        addedCount++;
      }
    });

    // Exercise Plan Routine Task
    if (state.exercisePlan && state.exercisePlan.title) {
      const exName = `Program Olahraga: ${state.exercisePlan.title}`;
      const exists = state.dailyTasks.some(t => t.date === dateStr && t.category === 'Olahraga');
      if (!exists) {
        const timeParts = state.exercisePlan.timeEst.split('-').map(s => s.trim());
        state.dailyTasks.push({
          id: 'task-auto-ex-' + Date.now(),
          date: dateStr,
          taskName: exName,
          category: 'Olahraga',
          timeStart: timeParts[0] || '06:00',
          timeEnd: timeParts[1] || '07:00',
          status: 'Pending',
          isAutoGenerated: true
        });
        addedCount++;
      }
    }

    saveState();
    renderDailyTasks();
    updateActiveTaskBanner(new Date());
    showToast(`Berhasil mengintegrasikan ${addedCount} rutinitas ke Daily Tasks!`, 'success');
  }

  btnAutoSyncDaily.addEventListener('click', () => autoSyncRoutinesForDate(state.selectedDate));
  btnEmptyAddTask.addEventListener('click', () => {
    resetTaskForm();
    openModal('modalTask');
  });

  // Task Modal Form Submission
  const formDailyTask = document.getElementById('formDailyTask');
  formDailyTask.addEventListener('submit', (e) => {
    e.preventDefault();
    const editId = document.getElementById('taskEditId').value;
    const name = document.getElementById('taskNameInput').value.trim();
    const cat = document.getElementById('taskCategorySelect').value;
    const status = document.getElementById('taskStatusSelect').value;
    const timeStart = document.getElementById('taskTimeStart').value;
    const timeEnd = document.getElementById('taskTimeEnd').value;

    if (editId) {
      const t = state.dailyTasks.find(x => x.id === editId);
      if (t) {
        t.taskName = name;
        t.category = cat;
        t.status = status;
        t.timeStart = timeStart;
        t.timeEnd = timeEnd;
      }
    } else {
      state.dailyTasks.push({
        id: 'task-' + Date.now(),
        date: state.selectedDate,
        taskName: name,
        category: cat,
        timeStart: timeStart,
        timeEnd: timeEnd,
        status: status,
        isAutoGenerated: false
      });
    }

    saveState();
    closeModal('modalTask');
    renderDailyTasks();
    updateActiveTaskBanner(new Date());
    showToast('Tugas berhasil disimpan!', 'success');
  });

  function resetTaskForm() {
    document.getElementById('taskEditId').value = '';
    document.getElementById('taskNameInput').value = '';
    document.getElementById('taskTimeStart').value = '08:00';
    document.getElementById('taskTimeEnd').value = '09:00';
    document.getElementById('modalTaskTitle').textContent = 'Tambah Tugas Baru';
  }

  // ==========================================================================
  // 5. MODUL IBADAH (Requirement 2.C)
  // ==========================================================================
  const prayerListContainer = document.getElementById('prayerListContainer');
  const chkDhuha = document.getElementById('chkDhuha');
  const chkTahajud = document.getElementById('chkTahajud');
  const inputQuranMinutes = document.getElementById('inputQuranMinutes');
  const btnSaveQuranMinutes = document.getElementById('btnSaveQuranMinutes');
  const quranMinutesDisplay = document.getElementById('quranMinutesDisplay');
  const quranProgressBar = document.getElementById('quranProgressBar');

  function renderIbadahModule() {
    ensureDateLogs(state.selectedDate);
    const log = state.ibadahLogs[state.selectedDate];

    // Render 5 Daily Prayers
    const prayers = ['Subuh', 'Dzuhur', 'Ashar', 'Maghrib', 'Isya'];
    prayerListContainer.innerHTML = '';

    prayers.forEach(pName => {
      const currentStatus = log.prayers[pName] || "Ada'";
      const item = document.createElement('div');
      item.className = 'prayer-item';

      item.innerHTML = `
        <div class="prayer-info">
          <div class="prayer-icon"><i class="fa-solid fa-mosque"></i></div>
          <div>
            <strong>Sholat ${pName}</strong>
            <br><small class="text-muted">Status: ${currentStatus}</small>
          </div>
        </div>
        <div class="prayer-status-options">
          <button class="prayer-opt-btn ${currentStatus === "Jama'ah" ? 'active' : ''}" data-prayer="${pName}" data-status="Jama'ah">Jama'ah</button>
          <button class="prayer-opt-btn ${currentStatus === "Ada'" ? 'active' : ''}" data-prayer="${pName}" data-status="Ada'">Ada'</button>
          <button class="prayer-opt-btn ${currentStatus === "Qada'" ? 'active' : ''}" data-prayer="${pName}" data-status="Qada'">Qada'</button>
        </div>
      `;

      prayerListContainer.appendChild(item);
    });

    // Event listener for prayer buttons
    prayerListContainer.querySelectorAll('.prayer-opt-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        const prayerName = btn.dataset.prayer;
        const statusVal = btn.dataset.status;
        state.ibadahLogs[state.selectedDate].prayers[prayerName] = statusVal;
        saveState();
        renderIbadahModule();
        showToast(`Status Sholat ${prayerName} diperbarui: ${statusVal}`, 'success');
      });
    });

    // Render Sunnah
    chkDhuha.checked = !!log.sunnah.Dhuha;
    chkTahajud.checked = !!log.sunnah.Tahajud;

    // Render Quran Minutes
    const mins = log.quranMinutes || 0;
    inputQuranMinutes.value = mins;
    quranMinutesDisplay.textContent = `${mins} Menit`;
    const progressPct = Math.min(100, Math.round((mins / 30) * 100)); // Target 30 mins
    quranProgressBar.style.width = `${progressPct}%`;
  }

  chkDhuha.addEventListener('change', (e) => {
    ensureDateLogs(state.selectedDate);
    state.ibadahLogs[state.selectedDate].sunnah.Dhuha = e.target.checked;
    saveState();
    showToast(`Sholat Dhuha: ${e.target.checked ? 'Melaksanakan' : 'Tidak'}`, 'success');
  });

  chkTahajud.addEventListener('change', (e) => {
    ensureDateLogs(state.selectedDate);
    state.ibadahLogs[state.selectedDate].sunnah.Tahajud = e.target.checked;
    saveState();
    showToast(`Sholat Tahajud: ${e.target.checked ? 'Melaksanakan' : 'Tidak'}`, 'success');
  });

  btnSaveQuranMinutes.addEventListener('click', () => {
    ensureDateLogs(state.selectedDate);
    const val = parseInt(inputQuranMinutes.value) || 0;
    state.ibadahLogs[state.selectedDate].quranMinutes = val;
    saveState();
    renderIbadahModule();
    showToast('Durasi Al-Qur\'an diperbarui!', 'success');
  });

  // ==========================================================================
  // 6. MODUL PERSONAL GOALS & STREAK (Requirement 2.D)
  // ==========================================================================
  const inputEnglishMinutes = document.getElementById('inputEnglishMinutes');
  const btnSaveEnglishMinutes = document.getElementById('btnSaveEnglishMinutes');
  const englishMinutesDisplay = document.getElementById('englishMinutesDisplay');
  const englishProgressBar = document.getElementById('englishProgressBar');

  const nofapStreakDays = document.getElementById('nofapStreakDays');
  const bestNoFapStreak = document.getElementById('bestNoFapStreak');
  const nofapStartDate = document.getElementById('nofapStartDate');
  const btnCheckInStreak = document.getElementById('btnCheckInStreak');
  const btnResetNoFap = document.getElementById('btnResetNoFap');

  const customGoalsGrid = document.getElementById('customGoalsGrid');
  const emptyGoalsState = document.getElementById('emptyGoalsState');
  const btnAddCustomGoalModal = document.getElementById('btnAddCustomGoalModal');

  function renderGoalsModule() {
    ensureDateLogs(state.selectedDate);
    const goalLog = state.goalLogs[state.selectedDate];

    // English Learning
    const engMins = goalLog.englishMinutes || 0;
    inputEnglishMinutes.value = engMins;
    englishMinutesDisplay.textContent = `${engMins} Menit`;
    const engPct = Math.min(100, Math.round((engMins / 60) * 100)); // Target 60 mins
    englishProgressBar.style.width = `${engPct}%`;

    // NoFap Streak
    nofapStreakDays.textContent = state.nofap.streak;
    bestNoFapStreak.textContent = `${state.nofap.bestStreak} Hari`;
    nofapStartDate.textContent = state.nofap.startDate || '--/--/----';

    // Render Custom Goals Grid
    renderCustomGoalsGrid();
  }

  btnSaveEnglishMinutes.addEventListener('click', () => {
    ensureDateLogs(state.selectedDate);
    const val = parseInt(inputEnglishMinutes.value) || 0;
    state.goalLogs[state.selectedDate].englishMinutes = val;
    saveState();
    renderGoalsModule();
    showToast('Durasi belajar Bahasa Inggris diperbarui!', 'success');
  });

  // NoFap Handlers
  btnCheckInStreak.addEventListener('click', () => {
    const today = getTodayStr();
    if (state.nofap.lastCheckInDate === today) {
      showToast('Anda sudah melakukan Check-in hari ini!', 'success');
      return;
    }
    state.nofap.streak += 1;
    if (state.nofap.streak > state.nofap.bestStreak) {
      state.nofap.bestStreak = state.nofap.streak;
    }
    state.nofap.lastCheckInDate = today;
    saveState();
    renderGoalsModule();
    showToast('🔥 Check-in berhasil! Streak bertambah +1 Hari', 'success');
  });

  btnResetNoFap.addEventListener('click', () => {
    if (confirm('Apakah Anda mengalami relapse? Streak akan direset ke 0 hari. Streak tertinggi Anda akan tetap tersimpan.')) {
      if (state.nofap.streak > state.nofap.bestStreak) {
        state.nofap.bestStreak = state.nofap.streak;
      }
      state.nofap.streak = 0;
      state.nofap.startDate = getTodayStr();
      state.nofap.lastCheckInDate = '';
      saveState();
      renderGoalsModule();
      showToast('Streak telah direset. Tetap semangat untuk membangun kembali!', 'error');
    }
  });

  // Custom Goals Handling
  function renderCustomGoalsGrid() {
    customGoalsGrid.innerHTML = '';

    if (state.customGoalsList.length === 0) {
      emptyGoalsState.style.display = 'block';
      return;
    }

    emptyGoalsState.style.display = 'none';
    const dayLog = state.customGoalLogs[state.selectedDate] || {};

    state.customGoalsList.forEach(goal => {
      const currentVal = dayLog[goal.id] !== undefined ? dayLog[goal.id] : 0;
      const card = document.createElement('div');
      card.className = 'goal-card';

      if (goal.type === 'boolean') {
        const isChecked = !!currentVal;
        card.innerHTML = `
          <div class="goal-card-header">
            <div>
              <strong>${escapeHtml(goal.title)}</strong>
              <small class="text-muted block mt-1">Target: Ya / Tidak</small>
            </div>
            <button class="btn btn-outline btn-sm btn-delete-goal" data-id="${goal.id}">&times;</button>
          </div>
          <div class="flex-between mt-2">
            <span>Status Hari Ini:</span>
            <label class="switch">
              <input type="checkbox" class="chk-custom-goal" data-id="${goal.id}" ${isChecked ? 'checked' : ''}>
              <span class="slider round"></span>
            </label>
          </div>
        `;
      } else {
        card.innerHTML = `
          <div class="goal-card-header">
            <div>
              <strong>${escapeHtml(goal.title)}</strong>
              <small class="text-muted block mt-1">Target: ${goal.target} ${goal.unit}</small>
            </div>
            <button class="btn btn-outline btn-sm btn-delete-goal" data-id="${goal.id}">&times;</button>
          </div>
          <div class="input-with-unit mt-2">
            <input type="number" class="form-control input-custom-goal" data-id="${goal.id}" value="${currentVal}" min="0" placeholder="0">
            <span class="unit">${goal.unit || 'unit'}</span>
          </div>
        `;
      }

      customGoalsGrid.appendChild(card);
    });

    // Custom Goal Change Events
    customGoalsGrid.querySelectorAll('.chk-custom-goal').forEach(chk => {
      chk.addEventListener('change', (e) => {
        ensureDateLogs(state.selectedDate);
        state.customGoalLogs[state.selectedDate][chk.dataset.id] = e.target.checked ? 1 : 0;
        saveState();
        showToast('Status custom goal diperbarui!', 'success');
      });
    });

    customGoalsGrid.querySelectorAll('.input-custom-goal').forEach(input => {
      input.addEventListener('change', (e) => {
        ensureDateLogs(state.selectedDate);
        const val = parseInt(e.target.value) || 0;
        state.customGoalLogs[state.selectedDate][input.dataset.id] = val;
        saveState();
        showToast('Capaian custom goal diperbarui!', 'success');
      });
    });

    customGoalsGrid.querySelectorAll('.btn-delete-goal').forEach(btn => {
      btn.addEventListener('click', () => {
        if (confirm('Hapus item custom goal ini?')) {
          state.customGoalsList = state.customGoalsList.filter(g => g.id !== btn.dataset.id);
          saveState();
          renderCustomGoalsGrid();
          showToast('Custom goal berhasil dihapus', 'success');
        }
      });
    });
  }

  btnAddCustomGoalModal.addEventListener('click', () => openModal('modalCustomGoal'));

  const formCustomGoal = document.getElementById('formCustomGoal');
  formCustomGoal.addEventListener('submit', (e) => {
    e.preventDefault();
    const title = document.getElementById('goalTitleInput').value.trim();
    const type = document.getElementById('goalTypeSelect').value;
    const unit = document.getElementById('goalUnitInput').value.trim();
    const target = parseInt(document.getElementById('goalTargetInput').value) || 1;

    state.customGoalsList.push({
      id: 'cg-' + Date.now(),
      title,
      type,
      unit,
      target
    });

    saveState();
    closeModal('modalCustomGoal');
    renderCustomGoalsGrid();
    showToast('Custom Goal baru berhasil ditambahkan!', 'success');
    formCustomGoal.reset();
  });

  // ==========================================================================
  // 7. MODUL OLAHRAGA (Requirement 2.E)
  // ==========================================================================
  const exerciseTargetTitle = document.getElementById('exerciseTargetTitle');
  const exerciseTargetDesc = document.getElementById('exerciseTargetDesc');
  const exerciseTargetMeta = document.getElementById('exerciseTargetMeta');
  const exerciseTargetDate = document.getElementById('exerciseTargetDate');
  const exerciseTotalDays = document.getElementById('exerciseTotalDays');
  const btnEditExercisePlan = document.getElementById('btnEditExercisePlan');
  const todayExerciseContainer = document.getElementById('todayExerciseContainer');

  function renderExerciseModule() {
    ensureDateLogs(state.selectedDate);
    const plan = state.exercisePlan;

    if (plan && plan.title) {
      exerciseTargetTitle.textContent = plan.title;
      exerciseTargetDesc.textContent = `Rentang Jam Rutin: ${plan.timeEst || '06:00 - 07:00'}`;
      exerciseTargetMeta.style.display = 'block';
      exerciseTargetDate.textContent = plan.targetDate || '--';
      exerciseTotalDays.textContent = plan.menus.length;
    }

    // Render Today's Menu Items with Action Statuses
    const todayLogs = state.exerciseDailyLogs[state.selectedDate] || [];
    todayExerciseContainer.innerHTML = '';

    if (todayLogs.length === 0) {
      todayExerciseContainer.innerHTML = `
        <div class="empty-state">
          <i class="fa-solid fa-dumbbell empty-icon"></i>
          <p>Belum ada menu latihan yang diset. Klik "Atur Plan Latihan" di atas.</p>
        </div>
      `;
      return;
    }

    const actionOptions = ['Pending', 'Done', 'Failed', 'Cancel', 'Swap with other exercise', 'Swap day'];

    todayLogs.forEach((item, idx) => {
      const div = document.createElement('div');
      div.className = 'exercise-routine-item';

      div.innerHTML = `
        <div>
          <strong>${idx + 1}. ${escapeHtml(item.exerciseName)}</strong>
          <br><small class="text-muted"><i class="fa-regular fa-clock"></i> Scheduled Today</small>
        </div>
        <div>
          <select class="exercise-action-select" data-index="${idx}">
            ${actionOptions.map(opt => `<option value="${opt}" ${item.status === opt ? 'selected' : ''}>${opt}</option>`).join('')}
          </select>
        </div>
      `;

      todayExerciseContainer.appendChild(div);
    });

    todayExerciseContainer.querySelectorAll('.exercise-action-select').forEach(sel => {
      sel.addEventListener('change', (e) => {
        const index = parseInt(sel.dataset.index);
        state.exerciseDailyLogs[state.selectedDate][index].status = e.target.value;
        saveState();
        showToast(`Status latihan diperbarui: ${e.target.value}`, 'success');
      });
    });
  }

  btnEditExercisePlan.addEventListener('click', () => {
    const plan = state.exercisePlan;
    document.getElementById('exPlanTitle').value = plan.title || '';
    document.getElementById('exPlanTargetDate').value = plan.targetDate || '';
    document.getElementById('exPlanTimeEst').value = plan.timeEst || '06:00 - 07:00';
    document.getElementById('exPlanMenus').value = (plan.menus || []).join('\n');
    openModal('modalExercisePlan');
  });

  const formExercisePlan = document.getElementById('formExercisePlan');
  formExercisePlan.addEventListener('submit', (e) => {
    e.preventDefault();
    const title = document.getElementById('exPlanTitle').value.trim();
    const targetDate = document.getElementById('exPlanTargetDate').value;
    const timeEst = document.getElementById('exPlanTimeEst').value.trim();
    const menusText = document.getElementById('exPlanMenus').value.trim();

    const menus = menusText.split('\n').map(s => s.trim()).filter(s => s.length > 0);

    state.exercisePlan = {
      title,
      targetDate,
      timeEst,
      menus
    };

    // Reset daily logs structure for selected date
    state.exerciseDailyLogs[state.selectedDate] = menus.map(m => ({ exerciseName: m, status: 'Pending' }));

    saveState();
    closeModal('modalExercisePlan');
    renderExerciseModule();
    showToast('Plan latihan berhasil diperbarui!', 'success');
  });

  // ==========================================================================
  // 8. GOOGLE SHEETS API SYNC ENGINE (Requirements Section 1)
  // ==========================================================================
  const gasWebAppUrl = document.getElementById('gasWebAppUrl');
  const btnPushToGas = document.getElementById('btnPushToGas');
  const btnPullFromGas = document.getElementById('btnPullFromGas');
  const gasSyncLogBox = document.getElementById('gasSyncLogBox');
  const gasSyncTimeText = document.getElementById('gasSyncTimeText');
  const gasSyncDetails = document.getElementById('gasSyncDetails');
  const sidebarSyncStatus = document.getElementById('sidebarSyncStatus');

  gasWebAppUrl.value = state.settings.gasUrl || '';
  gasWebAppUrl.addEventListener('change', (e) => {
    state.settings.gasUrl = e.target.value.trim();
    saveState();
  });

  function updateSyncStatusUI() {
    if (state.settings.lastSynced) {
      gasSyncTimeText.textContent = `Terakhir Sync: ${state.settings.lastSynced}`;
      sidebarSyncStatus.innerHTML = `<i class="fa-solid fa-circle-dot status-online"></i> <span>Synced (${state.settings.lastSynced})</span>`;
    } else {
      gasSyncTimeText.textContent = `Belum Pernah Sync`;
      sidebarSyncStatus.innerHTML = `<i class="fa-solid fa-circle-dot status-offline"></i> <span>Lokal (Offline)</span>`;
    }
  }

  // Push Data (Upload to Google Sheets)
  async function pushToGoogleSheets() {
    const url = state.settings.gasUrl || gasWebAppUrl.value.trim();
    if (!url) {
      showToast('Harap masukkan Web App URL Google Apps Script di menu Settings!', 'error');
      switchTab('sync-settings');
      return;
    }

    btnPushToGas.disabled = true;
    btnPushToGas.innerHTML = `<i class="fa-solid fa-spinner fa-spin"></i> Uploading...`;

    try {
      const payload = {
        action: 'push',
        timestamp: new Date().toISOString(),
        state: state
      };

      // Send via POST JSON
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' }, // Avoid CORS preflight issues with Apps Script
        body: JSON.stringify(payload)
      });

      const json = await res.json();
      if (json.status === 'success') {
        const timeNow = new Date().toLocaleTimeString('id-ID');
        state.settings.lastSynced = timeNow;
        saveState();
        gasSyncDetails.textContent = `Data berhasil di-upload ke Google Sheets pada ${timeNow}.`;
        showToast('🎉 Data berhasil di-upload (Push) ke Google Sheets!', 'success');
      } else {
        throw new Error(json.message || 'Respons server gagal');
      }
    } catch (e) {
      console.error('GAS Push Error:', e);
      gasSyncDetails.textContent = `Gagal upload: ${e.message}`;
      showToast(`Gagal Upload: ${e.message}. Pastikan URL Web App benar dan di-deploy sebagai "Anyone".`, 'error');
    } finally {
      btnPushToGas.disabled = false;
      btnPushToGas.innerHTML = `<i class="fa-solid fa-cloud-arrow-up"></i> Upload Data (Push)`;
    }
  }

  // Pull Data (Download from Google Sheets)
  async function pullFromGoogleSheets() {
    const url = state.settings.gasUrl || gasWebAppUrl.value.trim();
    if (!url) {
      showToast('Harap masukkan Web App URL Google Apps Script di menu Settings!', 'error');
      switchTab('sync-settings');
      return;
    }

    btnPullFromGas.disabled = true;
    btnPullFromGas.innerHTML = `<i class="fa-solid fa-spinner fa-spin"></i> Downloading...`;

    try {
      const fetchUrl = url + (url.includes('?') ? '&' : '?') + 'action=pull&t=' + Date.now();
      const res = await fetch(fetchUrl);
      const json = await res.json();

      if (json.status === 'success' && json.state) {
        state = { ...defaultState, ...json.state, settings: { ...state.settings } };
        const timeNow = new Date().toLocaleTimeString('id-ID');
        state.settings.lastSynced = timeNow;
        saveState();
        renderAllModules();
        gasSyncDetails.textContent = `Data berhasil di-download dari Google Sheets pada ${timeNow}.`;
        showToast('⚡ Data berhasil di-download (Pull) dari Google Sheets!', 'success');
      } else {
        throw new Error(json.message || 'Format data Google Sheets tidak valid');
      }
    } catch (e) {
      console.error('GAS Pull Error:', e);
      gasSyncDetails.textContent = `Gagal download: ${e.message}`;
      showToast(`Gagal Download: ${e.message}`, 'error');
    } finally {
      btnPullFromGas.disabled = false;
      btnPullFromGas.innerHTML = `<i class="fa-solid fa-cloud-arrow-down"></i> Download Data (Pull)`;
    }
  }

  btnPushToGas.addEventListener('click', pushToGoogleSheets);
  btnPullFromGas.addEventListener('click', pullFromGoogleSheets);

  // ==========================================================================
  // 9. PWA INSTALLATION & SERVICE WORKER
  // ==========================================================================
  let deferredPrompt = null;
  const btnInstallPwaSidebar = document.getElementById('btnInstallPwaSidebar');
  const btnInstallPwaSettings = document.getElementById('btnInstallPwaSettings');

  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('./sw.js')
      .then(reg => console.log('[SW] Service Worker Registered', reg))
      .catch(err => console.error('[SW] Registration failed:', err));
  }

  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e;
    if (btnInstallPwaSidebar) btnInstallPwaSidebar.style.display = 'block';
    if (btnInstallPwaSettings) btnInstallPwaSettings.style.display = 'inline-flex';
  });

  function triggerPwaInstall() {
    if (deferredPrompt) {
      deferredPrompt.prompt();
      deferredPrompt.userChoice.then((choiceResult) => {
        if (choiceResult.outcome === 'accepted') {
          showToast('Terima kasih telah menginstall HabitPulse PWA!', 'success');
        }
        deferredPrompt = null;
      });
    } else {
      showToast('PWA sudah terinstall atau belum didukung browser ini.', 'success');
    }
  }

  if (btnInstallPwaSidebar) btnInstallPwaSidebar.addEventListener('click', triggerPwaInstall);
  if (btnInstallPwaSettings) btnInstallPwaSettings.addEventListener('click', triggerPwaInstall);

  // ==========================================================================
  // 10. MODAL UTILITY & TOAST SYSTEM
  // ==========================================================================
  function openModal(modalId) {
    const el = document.getElementById(modalId);
    if (el) el.classList.add('active');
  }

  function closeModal(modalId) {
    const el = document.getElementById(modalId);
    if (el) el.classList.remove('active');
  }

  document.querySelectorAll('[data-close]').forEach(btn => {
    btn.addEventListener('click', () => {
      closeModal(btn.dataset.close);
    });
  });

  function showToast(message, type = 'info') {
    const container = document.getElementById('toastContainer');
    const toast = document.createElement('div');
    toast.className = `toast toast-${type}`;
    toast.innerHTML = `<i class="fa-solid ${type === 'success' ? 'fa-circle-check text-emerald' : 'fa-triangle-exclamation text-danger'}"></i> <span>${escapeHtml(message)}</span>`;
    container.appendChild(toast);

    setTimeout(() => {
      toast.style.opacity = '0';
      setTimeout(() => toast.remove(), 300);
    }, 3500);
  }

  function escapeHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // ==========================================================================
  // RENDER ALL MODULES
  // ==========================================================================
  function renderAllModules() {
    renderDailyTasks();
    renderIbadahModule();
    renderGoalsModule();
    renderExerciseModule();
    updateSyncStatusUI();
  }

  // Initial Run
  ensureDateLogs(state.selectedDate);
  updateRealTimeClock();
  renderAllModules();
});
